;;;;;;;;;;;;;
; sound.inc ;
;;;;;;;;;;;;;

; Description
; -----------
; constants for sound logic
;
; Constants
; ---------
; SPKR_PORT_BIT: the bit at which the speaker resides on its port
;
; Revision History
; ----------------
; 05/29/2022    Matt Muldowney      

; ports
; =====
; bit at which speaker resides on its respective port
; ---------------------------------------------------
.equ    SPKR_PORT_BIT = 5